from langgraph.graph import StateGraph, END
from typing import List, TypedDict, Annotated
import operator


class AgentState(TypedDict):
    # the original customer request
    user_request: str

    # structured search params generated by Qwen
    search_params: dict

    # current pool of candidate image IDs/Metadata
    candidate_pool: List[dict]

    # images that passed the reranker
    refined_pool: List[dict]

    # the final selection
    final_collection: List[dict]

    # feedback from the curator if more images are needed
    feedback: str

    # loop counter for safety
    iterations: int


# STAGE-0: Intent extraction
def planner_node(state: AgentState):
    # Call the OpenAI api and generate the search JSON
    # If state['feedback'] exists, tell Qwen to adjust the strategy
    return {
        "search_params": generated_params,
        "iterations": state.get("iterations", 0) + 1
    }


# STAGE-1: Generate Candidates (recall >> precision)
def retriever_node(state: AgentState):
    # 1. Use Qwen3-VL-Embedding to encode search_params
    # 2. Query Milvus/Qdrant for several thousand candidates
    return {"candidate_pool": results_from_db}


# STAGE-2: Reranking
def reranker_node(state: AgentState):
    # Score candidate_pool against user_request
    # Filter for top 200-500 images
    return {"refined_pool": ranked_results}


# STAGE-3: Final curation
def curator_node(state: AgentState):
    # Qwen 3.5 VL reviews the refined_pool for diversity & specific logic
    # Selects the best 100
    if len(best_100) < 100:
        return {"feedback": "Not enough images with soft lighting", "final_collection": best_100}
    return {"final_collection": best_100, "feedback": "done"}


#--- BUILD THE GRAPH -----------------------------------------------------------

workflow = StateGraph(AgentState)


# add the nodes
workflow.add_node("planner", planner_node)
workflow.add_node("retriever", retriever_node)
workflow.add_node("reranker", reranker_node)
workflow.add_node("curator", curator_node)

# set entry Point
workflow.set_entry_point("planner")

# define fixed edges
workflow.add_edge("planner", "retriever")
workflow.add_edge("retriever", "reranker")
workflow.add_edge("reranker", "curator")

# fefine conditional edge (the loop)
def should_continue(state: AgentState):
    if state["feedback"] == "done" or state["iterations"] > 3:
        return "end"
    return "continue"

workflow.add_conditional_edges(
    "curator", should_continue,
    {
        "continue": "planner", # loop back to refine the plan
        "end": END
    }
)

app = workflow.compile()