from langgraph.graph import StateGraph, END
from typing import List, Optional, TypedDict, Literal

from .curator import curator_node
from .planner import run_intent_node
from .retriever import run_retriever_node
from .schemas import IntentResult
from app.services.file_extractor import file_extractor
from app.services.image_analyzer import analyze_images

try:
    from .reranker import run_reranker_node
except Exception:
    run_reranker_node = None


class AgentState(TypedDict):
    # the original customer request
    user_request: str
    openai_api_key: Optional[str]

    # Optional raw file payload provided by the caller (e.g. API layer).
    # If present, brief_preprocess_node extracts text + image signals.
    uploaded_file_bytes: Optional[bytes]
    uploaded_file_name: Optional[str]

    # File extraction outputs (written by brief_preprocess_node)
    file_type: Optional[str]
    file_images: List[dict]
    image_analysis: Optional[dict]
    extraction_error: Optional[str]

    # optional context extracted from an uploaded file (PDF/DOCX/TXT).
    # populated by the caller before invoking the graph
    attachment_text: Optional[str]
    brief_quality: Optional[Literal["strong", "partial", "weak", "insufficient"]]
    brief_gaps: List[str]
    brief_warnings: List[str]
    can_search: Optional[bool]
    pdf_search_detail: Optional[dict]

    # structured search params generated by Stage 0 planner
    search_params: Optional[IntentResult]

    # current pool of candidate image IDs/Metadata (written by Stage 1)
    candidate_pool: List[dict]

    # images that passed the reranker (written by Stage 2)
    # Each item must conform to CandidateRecord in schemas.py:
    #   asset_id, origin_lane_name, thumbnail_url, stage2_score, media_type, title
    refined_pool: List[dict]

    # --- Stage 3 intermediate state ---

    # Candidates after per-image visual scoring (written by score_candidates_node)
    stage3_candidates: List[dict]

    # Top 100 shortlist, per-lane capped at 20 (written by shortlist_candidates_node)
    stage3_shortlist: List[dict]

    # Per-lane diversity audit dicts (written by audit_lanes_node)
    stage3_lane_audits: List[dict]

    # Repair requests produced by the last audit (written by curator_node)
    stage3_repair_requests: List[dict]

    # --- Shared loop state ---

    # The final curated selection (set by audit_lanes_node when feedback == "done")
    final_collection: List[dict]

    # Feedback from Stage 3 audit back to the planner.
    # "done"  → pipeline complete, final_collection is ready.
    # <text>  → repair description; planner will refine search_params and loop.
    feedback: str

    # Loop counter — pipeline terminates after 3 iterations regardless of feedback
    iterations: int


# PRE-STAGE: Brief preprocessing (optional file extraction + image analysis)
def brief_preprocess_node(state: AgentState):
    file_bytes = state.get("uploaded_file_bytes")
    file_name = state.get("uploaded_file_name") or "uploaded-file"
    existing_attachment = state.get("attachment_text") or ""

    # No file provided — pass through current attachment_text unchanged.
    if not file_bytes:
        return {
            "file_type": state.get("file_type"),
            "file_images": state.get("file_images", []),
            "image_analysis": state.get("image_analysis"),
            "extraction_error": state.get("extraction_error"),
        }

    # If the caller already provided extraction + image analysis context
    # (e.g. /chat route preprocessed once), reuse it to avoid duplicate work.
    if (
        state.get("file_type")
        or state.get("file_images")
        or state.get("image_analysis")
        or state.get("attachment_text")
        or state.get("extraction_error")
    ):
        return {
            "attachment_text": state.get("attachment_text"),
            "file_type": state.get("file_type"),
            "file_images": state.get("file_images", []),
            "image_analysis": state.get("image_analysis"),
            "extraction_error": state.get("extraction_error"),
        }

    extraction = file_extractor.extract_text_and_images(file_bytes, file_name)
    if extraction.get("error"):
        return {
            "file_type": extraction.get("file_type"),
            "file_images": [],
            "image_analysis": None,
            "extraction_error": extraction["error"],
        }

    extracted_text = extraction.get("text") or ""
    images = extraction.get("images") or []
    image_analysis = (
        analyze_images(images, api_key=state.get("openai_api_key"))
        if images
        else None
    )

    parts = [existing_attachment]
    if extracted_text:
        parts.append(extracted_text)

    # Keep attachment_text focused on extracted document text.
    # Image analysis is stored in state and injected into planner LLM context
    # at prompt-build time (see planner_node), rather than baked into node output.
    attachment_text = "\n\n".join(p for p in parts if p).strip() or None

    return {
        "attachment_text": attachment_text,
        "file_type": extraction.get("file_type"),
        "file_images": images,
        "image_analysis": image_analysis,
        "extraction_error": None,
    }


def _format_image_analysis_for_llm(image_analysis: Optional[dict]) -> Optional[str]:
    if not image_analysis:
        return None

    lines = ["IMAGE ANALYSIS CONTEXT (from uploaded brief visuals):"]
    summary = image_analysis.get("summary")
    if summary:
        lines.append(f"- Summary: {summary}")

    analysis_source = image_analysis.get("analysis_source")
    if analysis_source:
        lines.append(f"- Analysis source: {analysis_source}")

    palette = image_analysis.get("global_palette") or []
    if palette:
        palette_text = ", ".join(
            f"{c.get('name')} ({c.get('hex')})"
            for c in palette[:6]
            if isinstance(c, dict)
        )
        if palette_text:
            lines.append(f"- Dominant palette: {palette_text}")

    def _append_list(label: str, key: str, limit: int = 10):
        values = image_analysis.get(key) or []
        if isinstance(values, list) and values:
            cleaned = [str(v).strip() for v in values if str(v).strip()]
            if cleaned:
                lines.append(f"- {label}: {', '.join(cleaned[:limit])}")

    _append_list("Search terms", "search_terms", limit=12)
    _append_list("Objects", "objects", limit=10)
    _append_list("Scenes", "scenes", limit=10)
    _append_list("Text in image", "text_in_image", limit=8)
    _append_list("Scene phrases", "scene_phrases", limit=10)
    _append_list("Visual style terms", "visual_style_terms", limit=8)
    _append_list("Object-color phrases", "object_color_phrases", limit=8)

    return "\n".join(lines) if len(lines) > 1 else None


def _assess_brief_readiness(
    state: AgentState,
    search_params: Optional[IntentResult],
) -> tuple[Literal["strong", "partial", "weak", "insufficient"], List[str], List[str], bool]:
    """
    Mirror AgentSquad brief-readiness checks for SearchByBrief.
    """
    file_content = (state.get("attachment_text") or "").strip()
    file_images = state.get("file_images") or []
    image_analysis = state.get("image_analysis") or {}
    is_pdf = (state.get("file_type") or "").lower() == "pdf"
    image_count = len(file_images)

    sp = (
        search_params.model_dump()
        if hasattr(search_params, "model_dump")
        else (search_params or {})
    )
    if not isinstance(sp, dict):
        sp = {}
    hard_constraints = sp.get("hard_constraints") or {}
    search_lanes = sp.get("search_lanes") or []

    subjects_required = [
        str(v).strip()
        for v in (hard_constraints.get("subjects_required") or [])
        if str(v).strip()
    ]
    locations_required = [
        str(v).strip()
        for v in (hard_constraints.get("location_required") or [])
        if str(v).strip()
    ]
    semantic_terms: list[str] = []
    for lane in search_lanes:
        if not isinstance(lane, dict):
            continue
        semantic_terms.extend(
            [term for term in str(lane.get("embedding_query") or "").split() if term.strip()]
        )

    has_text = bool(file_content and len(file_content) >= 40)
    has_images = image_count > 0
    has_image_analysis = bool(
        image_analysis.get("search_terms")
        or image_analysis.get("object_color_phrases")
        or image_analysis.get("objects")
        or image_analysis.get("scenes")
        or image_analysis.get("summary")
    )
    has_lexical = len(subjects_required) >= 2
    has_semantic = len(semantic_terms) >= 4
    has_brand_domain = bool(subjects_required)
    # SearchByBrief no longer uses category matching in preprocessing/readiness.
    # Keep this as neutral-true so category warnings do not fire.
    has_categories = True
    has_named_entities = bool(locations_required)
    has_supporting_requirements = bool(
        hard_constraints.get("composition_required")
        or hard_constraints.get("style_required")
        or hard_constraints.get("licensing_required")
    )

    score = (
        (2 if has_text else 0)
        + (1 if has_images else 0)
        + (1 if has_image_analysis else 0)
        + (2 if has_lexical else 0)
        + (2 if has_semantic else 0)
        + (1 if has_brand_domain else 0)
        + (1 if has_categories else 0)
        + (1 if has_named_entities else 0)
        + (1 if has_supporting_requirements else 0)
    )

    gap_rules = [
        (not has_text, "No usable text was extracted from the uploaded file."),
        (is_pdf and not has_images, "No images were found in the uploaded PDF."),
        (not has_lexical, "We could not extract enough concrete keywords from the brief."),
        (not has_semantic, "The semantic search query is too thin to strongly guide retrieval."),
        (not has_brand_domain, "No clear subject, product, or brand domain was identified."),
    ]
    gaps = [message for condition, message in gap_rules if condition]

    warning_rules = [
        (not has_text and has_images, "No usable text was extracted from the uploaded file, so search relied mainly on image-derived signals."),
        (not has_named_entities, "No named entities were extracted from the brief, so results may be broader."),
        (is_pdf and not has_images, "No images were found in the uploaded PDF, so search relied on extracted text only."),
        (is_pdf and has_images and image_count <= 2, "2 or fewer images were found in the uploaded PDF, so visual guidance may be limited."),
        ((not has_lexical) or (not has_semantic), "Only a limited number of concrete keywords were extracted, which may reduce search precision."),
    ]
    warnings = [message for condition, message in warning_rules if condition]

    if score >= 7:
        quality: Literal["strong", "partial", "weak", "insufficient"] = "strong"
    elif score >= 5:
        quality = "partial"
    elif score >= 3:
        quality = "weak"
    else:
        quality = "insufficient"

    return quality, gaps, warnings, True


# STAGE-0: Intent extraction
def planner_node(state: AgentState):
    # On the first iteration, use the file attachment text as-is.
    # On repair iterations, pass the CURRENT search plan + curator feedback so
    # the planner can apply surgical updates rather than re-deriving from scratch.
    base_attachment_parts = [state.get("attachment_text") or ""]
    image_context = _format_image_analysis_for_llm(state.get("image_analysis"))
    if image_context:
        base_attachment_parts.append(image_context)
    base_attachment = "\n\n".join(p for p in base_attachment_parts if p).strip()
    feedback = state.get("feedback", "")
    existing_params = state.get("search_params")

    if feedback and feedback != "done":
        # Serialise the current plan so the planner knows which lanes already exist.
        existing_plan_text = ""
        if existing_params is not None:
            plan_dict = (
                existing_params.model_dump()
                if hasattr(existing_params, "model_dump")
                else existing_params
            )
            existing_plan_text = (
                "CURRENT SEARCH PLAN (existing IntentResult — patch this, do not rederive):\n"
                + __import__("json").dumps(plan_dict, indent=2)
            )
        attachment_text = "\n\n".join(filter(None, [base_attachment, existing_plan_text, feedback]))
    else:
        attachment_text = base_attachment or None

    # On repair iterations the full brief would cause the LLM to re-derive the plan
    # from scratch rather than applying the patch directives. Suppress it so the LLM
    # is forced to work from the CURRENT SEARCH PLAN + feedback only.
    if feedback and feedback != "done":
        brief_text = "[Original brief suppressed — apply the REPAIR LANE directives from CURATOR REPAIR FEEDBACK to the CURRENT SEARCH PLAN in the attachment. Write brand new embedding_queries from the lane_goal for each flagged lane. Do not re-derive the plan from scratch.]"
    else:
        brief_text = state["user_request"]

    search_params = run_intent_node(
        brief_text=brief_text,
        attachment_text=attachment_text,
        api_key_override=state.get("openai_api_key"),
    )
    brief_quality, brief_gaps, brief_warnings, can_search = _assess_brief_readiness(
        state=state,
        search_params=search_params,
    )
    image_analysis = state.get("image_analysis") or {}
    image_search_terms = image_analysis.get("search_terms") or []
    if not isinstance(image_search_terms, list):
        image_search_terms = []
    image_additions = [str(v).strip() for v in image_search_terms if str(v).strip()][:4]
    pdf_search_detail = {
        "images_extracted": len(state.get("file_images") or []),
        "text_extracted": bool((state.get("attachment_text") or "").strip()),
        "enrichment_added": image_additions,
        "quality": brief_quality,
        "gaps": brief_gaps,
        "warnings": brief_warnings,
    }

    return {
        "search_params": search_params,
        "iterations": state.get("iterations", 0) + 1,
        "brief_quality": brief_quality,
        "brief_gaps": brief_gaps,
        "brief_warnings": brief_warnings,
        "can_search": can_search,
        "pdf_search_detail": pdf_search_detail,
    }


# STAGE-1: Generate Candidates (recall >> precision)
def retriever_node(state: AgentState):
    # 1. Ideally use Qwen3-VL-Embedding to encode search_params but we only have CLIP for now...
    # 2. Query Milvus/Qdrant for several thousand candidates
    return run_retriever_node(state)


# STAGE-2: Reranking
def reranker_node(state: AgentState):
    # TEMP BYPASS:
    # We currently skip Stage-2 reranking because the reranker model is not
    # loaded in this environment. Keep run_reranker_node import/code intact,
    # but map Stage-1 candidates into the Stage-3 expected refined_pool shape.
    #
    # To re-enable reranking later, replace this return with:
    #   return run_reranker_node(state)
    candidate_pool = state.get("candidate_pool", [])
    refined_pool: list[dict] = []

    for item in candidate_pool:
        asset_id = str(item.get("asset_id", ""))
        origin_lanes = item.get("origin_lane_names", []) or []
        origin_lane_name = origin_lanes[0] if origin_lanes else "unknown-lane"

        # Stage 3 requires thumbnail_url + stage2_score fields.
        refined_pool.append(
            {
                "asset_id": asset_id,
                "origin_lane_name": origin_lane_name,
                "thumbnail_url": (
                    f"https://image.shutterstock.com/image-photo/"
                    f"words-words-words-words-260nw-{asset_id}.jpg"
                ),
                # Neutral placeholder score while reranker is bypassed.
                "stage2_score": 0.75,
                "media_type": "image",
                "title": f"Asset {asset_id}",
            }
        )

    return {"refined_pool": refined_pool}


#--- BUILD THE GRAPH -----------------------------------------------------------

workflow = StateGraph(AgentState)


# add the nodes
workflow.add_node("brief_preprocess", brief_preprocess_node)
workflow.add_node("planner", planner_node)
workflow.add_node("retriever", retriever_node)
workflow.add_node("reranker", reranker_node)
workflow.add_node("curator", curator_node)

# set entry Point
workflow.set_entry_point("brief_preprocess")

# define fixed edges
workflow.add_edge("brief_preprocess", "planner")
workflow.add_edge("planner", "retriever")
workflow.add_edge("retriever", "reranker")
workflow.add_edge("reranker", "curator")

# define conditional edge (the loop)
# curator_node checks the median stage3_score of the shortlist. If it clears
# MEDIAN_SCORE_THRESHOLD the pipeline ends. If not, it runs a lane audit to
# generate targeted repair directives and loops back to the planner.
# The iterations guard caps loops at 3 regardless of score.
def should_continue(state: AgentState):
    feedback = state.get("feedback", "")
    if feedback == "done":
        return "end"
    if state.get("iterations", 0) > 3:
        # Hard cap reached — promote shortlist to final_collection if not already set
        # so callers always have a result regardless of audit outcome.
        if not state.get("final_collection"):
            state["final_collection"] = state.get("stage3_shortlist") or []
        return "end"
    return "continue"

workflow.add_conditional_edges(
    "curator", should_continue,
    {
        "continue": "planner",  # loop back: planner refines plan with repair directives
        "end": END,
    }
)

app = workflow.compile()
