from langgraph.graph import StateGraph, END
from typing import List, Optional, TypedDict

from .curator import curator_node
from .planner import run_intent_node
from .schemas import IntentResult


class AgentState(TypedDict):
    # the original customer request
    user_request: str

    # optional context extracted from an uploaded file (PDF/DOCX/TXT).
    # populated by the caller before invoking the graph
    attachment_text: Optional[str]

    # structured search params generated by Stage 0 planner
    search_params: Optional[IntentResult]

    # current pool of candidate image IDs/Metadata (written by Stage 1)
    candidate_pool: List[dict]

    # images that passed the reranker (written by Stage 2)
    # Each item must conform to CandidateRecord in schemas.py:
    #   asset_id, origin_lane_name, thumbnail_url, stage2_score, media_type, title
    refined_pool: List[dict]

    # --- Stage 3 intermediate state ---

    # Candidates after per-image visual scoring (written by score_candidates_node)
    stage3_candidates: List[dict]

    # Top 100 shortlist, per-lane capped at 20 (written by shortlist_candidates_node)
    stage3_shortlist: List[dict]

    # Per-lane diversity audit dicts (written by audit_lanes_node)
    stage3_lane_audits: List[dict]

    # Repair requests produced by the last audit (written by curator_node)
    stage3_repair_requests: List[dict]

    # --- Shared loop state ---

    # The final curated selection (set by audit_lanes_node when feedback == "done")
    final_collection: List[dict]

    # Feedback from Stage 3 audit back to the planner.
    # "done"  → pipeline complete, final_collection is ready.
    # <text>  → repair description; planner will refine search_params and loop.
    feedback: str

    # Loop counter — pipeline terminates after 3 iterations regardless of feedback
    iterations: int


# STAGE-0: Intent extraction
def planner_node(state: AgentState):
    # On the first iteration, use the file attachment text as-is.
    # On repair iterations, pass the CURRENT search plan + curator feedback so
    # the planner can apply surgical updates rather than re-deriving from scratch.
    base_attachment = state.get("attachment_text") or ""
    feedback = state.get("feedback", "")
    existing_params = state.get("search_params")

    if feedback and feedback != "done":
        # Serialise the current plan so the planner knows which lanes already exist.
        existing_plan_text = ""
        if existing_params is not None:
            plan_dict = (
                existing_params.model_dump()
                if hasattr(existing_params, "model_dump")
                else existing_params
            )
            existing_plan_text = (
                "CURRENT SEARCH PLAN (existing IntentResult — patch this, do not rederive):\n"
                + __import__("json").dumps(plan_dict, indent=2)
            )
        attachment_text = "\n\n".join(filter(None, [base_attachment, existing_plan_text, feedback]))
    else:
        attachment_text = base_attachment or None

    # On repair iterations the full brief would cause the LLM to re-derive the plan
    # from scratch rather than applying the patch directives. Suppress it so the LLM
    # is forced to work from the CURRENT SEARCH PLAN + feedback only.
    if feedback and feedback != "done":
        brief_text = "[Original brief suppressed — apply the UPDATE LANE directives from CURATOR REPAIR FEEDBACK to the CURRENT SEARCH PLAN in the attachment. Do not re-derive the plan from scratch.]"
    else:
        brief_text = state["user_request"]

    search_params = run_intent_node(
        brief_text=brief_text,
        attachment_text=attachment_text,
    )

    return {
        "search_params": search_params,
        "iterations": state.get("iterations", 0) + 1,
    }


# STAGE-1: Generate Candidates (recall >> precision)
def retriever_node(state: AgentState):
    # -------------------------------------------------------------------------
    # STAGE 1 HANDOVER CONTRACT 
    # -------------------------------------------------------------------------
    # Inputs consumed from state:
    #   state["search_params"]  — IntentResult from Stage 0 planner
    #     • search_params.search_lanes     — list of SearchLane; run one vector
    #                                        search per lane using embedding_query
    #     • search_params.shared_filters   — apply to every lane query
    #     • search_params.hard_constraints — use exclusions + licensing_required
    #                                        as post-retrieval filters
    #
    # Algorithm:
    #   1. For each lane in search_params.search_lanes:
    #        a. Embed lane.embedding_query using Qwen3-VL-Embedding-8B
    #        b. Query the vector store (top-k ≥ 500 per lane)
    #        c. Apply shared_filters + lane.lane_filters
    #   2. Merge per-lane results; deduplicate by asset_id
    #
    # Output — each item in candidate_pool MUST carry:
    #   asset_id           (int | str)  — unique image identifier
    #   origin_lane_name   (str)        — exactly matches the lane_name used for retrieval
    #   thumbnail_url      (str)        — publicly accessible image URL;
    #                                    Stage 3 SKIPS visual scoring if this is absent
    #   media_type         (str)        — optional, e.g. "photo"
    #   title              (str)        — optional, human-readable title
    # -------------------------------------------------------------------------
    return {"candidate_pool": results_from_db}


# STAGE-2: Reranking
def reranker_node(state: AgentState):
    # -------------------------------------------------------------------------
    # STAGE 2 HANDOVER CONTRACT 
    # -------------------------------------------------------------------------
    # Inputs consumed from state:
    #   state["candidate_pool"] — output of retriever_node
    #   state["search_params"]  — IntentResult (ranking_hints per lane available)
    #
    # Algorithm:
    #   Score every candidate in candidate_pool against user_request using
    #   Qwen3-VL-Reranker-8B cross-encoder. Discard candidates scoring < 0.7.
    #   Target 250–500 survivors written to refined_pool.
    #
    # Output — each item in refined_pool MUST preserve all candidate_pool fields
    # AND add:
    #   stage2_score  (float 0.0–1.0) — cross-encoder relevance score;
    #                                   primary input to Stage 3 weighted scoring
    # -------------------------------------------------------------------------
    return {"refined_pool": ranked_results}


#--- BUILD THE GRAPH -----------------------------------------------------------

workflow = StateGraph(AgentState)


# add the nodes
workflow.add_node("planner", planner_node)
workflow.add_node("retriever", retriever_node)
workflow.add_node("reranker", reranker_node)
workflow.add_node("curator", curator_node)

# set entry Point
workflow.set_entry_point("planner")

# define fixed edges
workflow.add_edge("planner", "retriever")
workflow.add_edge("retriever", "reranker")
workflow.add_edge("reranker", "curator")

# define conditional edge (the loop)
# curator_node checks the median stage3_score of the shortlist. If it clears
# MEDIAN_SCORE_THRESHOLD the pipeline ends. If not, it runs a lane audit to
# generate targeted repair directives and loops back to the planner.
# The iterations guard caps loops at 3 regardless of score.
def should_continue(state: AgentState):
    feedback = state.get("feedback", "")
    if feedback == "done":
        return "end"
    if state.get("iterations", 0) > 3:
        # Hard cap reached — promote shortlist to final_collection if not already set
        # so callers always have a result regardless of audit outcome.
        if not state.get("final_collection"):
            state["final_collection"] = state.get("stage3_shortlist") or []
        return "end"
    return "continue"

workflow.add_conditional_edges(
    "curator", should_continue,
    {
        "continue": "planner",  # loop back: planner refines plan with repair directives
        "end": END,
    }
)

app = workflow.compile()